'use strict';
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let minimum=5;
let sessions=[],selected=new Set(),adminKey='',adminData=null,pending=null,receipt=null,view='signup';
const newPin=()=>String(crypto.getRandomValues(new Uint32Array(1))[0]%10000).padStart(4,'0');
const date=s=>new Date(s.date+'T12:00:00').toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'});
const label=s=>`${date(s)} · ${s.start.replace(':',' h ')}–${s.end.replace(':',' h ')}`;
const fee=s=>s.price==='don'?'Don libre':s.price==='tiny3'?'4 € NTP · don libre NC':s.price===0?'Gratuit':s.price+' €';
const unavailable=s=>s.status==='cancelled'||s.past||(s.capacity!==null&&s.count>=s.capacity);
const state=s=>s.status==='cancelled'?['Annulée','cancelled']:s.past?['Séance passée','']:s.status==='confirmed'&&s.count>=minimum?['Confirmée par le club','confirmed']:s.status==='confirmed'&&s.count<minimum?[`À reconfirmer : moins de ${minimum} inscrits`,'']:s.count>=minimum?['Seuil atteint','ready']:[`Encore ${minimum-s.count} inscrit${minimum-s.count>1?'s':''} pour atteindre le seuil`,''];
function message(text){$('feedback').textContent=text;}
async function api(path,{body,key}={}){const response=await fetch(window.ROC_API+path,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(key?{Authorization:'Bearer '+key}:{})},...(body?{body:JSON.stringify(body)}:{})});let data;try{data=await response.json();}catch{throw new Error('Le service est momentanément indisponible. Réessayez.');}if(!response.ok)throw Object.assign(new Error(data.error||'Le service est indisponible.'),{code:data.code});return data;}
function card(s,choose=false){const [text,cls]=state(s);return `<article class="card${selected.has(s.id)?' selected':''}"><div class="date">${esc(date(s))}</div><h3>${esc(s.group)}</h3><div class="time">${esc(s.start)} – ${esc(s.end)}</div><div class="meta"><strong>${esc(fee(s))}</strong><span>${esc(s.location)}</span></div><div class="badge ${cls}">${esc(text)}</div><progress max="${minimum}" value="${Math.min(minimum,s.count)}" aria-label="${s.count} inscrits sur un minimum de ${minimum}"></progress><p><strong>${s.count} inscrit${s.count>1?'s':''}</strong>${s.capacity!==null?` · ${s.capacity} places au total`:''}</p>${s.note?`<p class="muted">${esc(s.note)}</p>`:''}${choose?`<button type="button" data-select="${s.id}" ${unavailable(s)&&!selected.has(s.id)?'disabled':''}>${selected.has(s.id)?'Retirer de ma sélection':s.status==='cancelled'?'Séance annulée':s.past?'Séance passée':s.capacity!==null&&s.count>=s.capacity?'Complet':'Choisir ce créneau'}</button>`:''}</article>`;}
function stats(data,regs){const total=regs?.length??data.reduce((n,s)=>n+s.count,0),ready=data.filter(s=>s.count>=minimum&&s.status!=='cancelled').length,confirmed=data.filter(s=>s.status==='confirmed'&&s.count>=minimum).length;return `<div class="stat"><strong>${total}</strong>inscriptions aux créneaux</div><div class="stat"><strong>${ready}</strong>sessions au seuil de ${minimum}</div><div class="stat"><strong>${confirmed}</strong>sessions confirmées</div>`;}
function render(){const group=$('group').value,week=$('week').value;const filtered=sessions.filter(s=>(!group||s.eligibleGroups.includes(group))&&(week==='all'||s.week===Number(week)));$('loadState').textContent=group?`${filtered.length} créneaux proposés pour ${group}`:'Choisissez votre groupe pour afficher les créneaux.';$('sessions').innerHTML=group?filtered.map(s=>card(s,true)).join(''):'';$('trackingCards').innerHTML=sessions.map(s=>card(s)).join('');$('stats').innerHTML=stats(sessions);$('registration').hidden=!selected.size;const tiny3=group==='Tiny 3'&&sessions.some(s=>selected.has(s.id)&&s.price==='tiny3');$('licenceWrap').hidden=!tiny3;$('registration').elements.licence.required=tiny3;$('selection').innerHTML=`<strong>${selected.size} créneau${selected.size>1?'x':''} sélectionné${selected.size>1?'s':''}</strong><ul>${sessions.filter(s=>selected.has(s.id)).map(s=>`<li>${esc(label(s))} — ${esc(fee(s))}</li>`).join('')}</ul>`;}
async function load(){try{const data=await api('/api/sessions');sessions=data.sessions;minimum=data.minimum||5;render();}catch(e){message(e.message);$('loadState').textContent='Impossible de charger les effectifs. Actualisez pour réessayer.';}}
function show(id){view=id;for(const s of ['signup','tracking','manage','club'])$(s).hidden=s!==id;for(const [tab,section]of[['signupTab','signup'],['trackingTab','tracking'],['manageTab','manage']])$(tab).classList.toggle('active',id===section);message('');}
for(const [tab,id]of[['signupTab','signup'],['trackingTab','tracking'],['manageTab','manage'],['adminOpen','club']])$(tab).onclick=()=>{show(id);if(id==='tracking')load();};
$('group').onchange=()=>{selected.clear();pending=null;render();};$('week').onchange=render;$('refresh').onclick=()=>{message('');load();};
$('sessions').onclick=e=>{const id=e.target.closest('[data-select]')?.dataset.select;if(!id)return;selected.has(id)?selected.delete(id):selected.add(id);pending=null;render();};
$('registration').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target);const base={name:form.get('name'),email:form.get('email'),licence:form.get('licence'),group:$('group').value,consent:form.get('consent')==='on',sessions:[...selected]};const signature=JSON.stringify(base);if(!pending||pending.signature!==signature)pending={signature,id:crypto.randomUUID(),token:newPin()};$('submit').disabled=true;message('');try{for(let attempt=0;attempt<5;attempt++){try{await api('/api/register',{body:{...base,id:pending.id,token:pending.token}});break;}catch(error){if(error.code!=='PIN_COLLISION'||attempt===4)throw error;pending.token=newPin();}};receipt={...base,code:pending.token,sessions:sessions.filter(s=>selected.has(s.id))};$('receiptCode').value=receipt.code;$('bookingCode').value=receipt.code;$('bookingEmail').value=base.email;$('legacyCode').value='';$('receiptSummary').innerHTML=`<p><strong>${esc(base.name)}</strong> · ${esc(base.group)}</p><ul>${receipt.sessions.map(s=>`<li>${esc(label(s))} — ${esc(fee(s))}</li>`).join('')}</ul><p>Votre demande est enregistrée. Consultez le suivi des effectifs pour connaître le statut des sessions.</p>`;$('receipt').showModal();selected.clear();pending=null;await load();}catch(error){message(error.message);await load();}finally{$('submit').disabled=false;}};
$('closeReceipt').onclick=()=>$('receipt').close();
function download(filename,body,type){const url=URL.createObjectURL(new Blob([body],{type}));const link=document.createElement('a');link.href=url;link.download=filename;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
$('saveReceipt').onclick=()=>download('ROC-mon-inscription-Toussaint.txt',`ROC — Stages de la Toussaint 2026\n${receipt.name} — ${receipt.group}\n\n${receipt.sessions.map(s=>label(s)+' — '+fee(s)).join('\n')}\n\nCode personnel à 4 chiffres :\n${receipt.code}\nE-mail de l’inscription : ${receipt.email}\n\nRetrouver mon inscription : ${location.href.split('#')[0]}\nAucun e-mail automatique n’est envoyé.\n`, 'text/plain;charset=utf-8');
function code(){const legacy=$('legacyCode').value.trim();if(legacy){const parts=legacy.split('.');if(parts.length!==2)throw new Error('Collez votre ancien code personnel complet.');return {id:parts[0],token:parts[1]};}const token=$('bookingCode').value.trim(),email=$('bookingEmail').value.trim();if(!/^[0-9]{4}$/.test(token))throw new Error('Indiquez votre code personnel à 4 chiffres.');if(!/^\S+@\S+\.\S+$/.test(email))throw new Error('Indiquez l’e-mail utilisé lors de votre inscription.');return {email,token};}
function renderBooking(b){$('myBooking').innerHTML=`<h3>${esc(b.name)} · ${esc(b.group)}</h3>${b.sessions.length?`<div class="cards">${b.sessions.map(s=>`<article class="card"><strong>${esc(label(s))}</strong><span>${esc(s.priceLabel)}</span><span class="badge">${esc(state(s)[0])}</span><button data-cancel="${s.id}" class="secondary" ${s.past?'disabled':''}>Annuler ce créneau</button></article>`).join('')}</div>`:'<p>Aucun créneau actif dans cette inscription.</p>'}`;}
$('lookup').onsubmit=async e=>{e.preventDefault();try{renderBooking(await api('/api/booking',{body:code()}));message('');}catch(error){message(error.message);}};
$('myBooking').onclick=async e=>{const id=e.target.closest('[data-cancel]')?.dataset.cancel;if(!id||!confirm('Confirmez-vous l’annulation de ce créneau ?'))return;try{renderBooking(await api('/api/cancel',{body:{...code(),sessions:[id]}}));await load();message('Le créneau a été annulé.');}catch(error){message(error.message);}};
async function loadAdmin(){adminData=await api('/api/admin',{key:adminKey});$('adminStats').innerHTML=stats(adminData.sessions,adminData.registrations.filter(r=>!r.retired));$('adminSessions').innerHTML=adminData.sessions.map(s=>{const regs=adminData.registrations.filter(r=>r.session_id===s.id);return `<article class="admin-session"><h3>${esc(s.group)} · ${esc(label(s))}</h3><p><strong>${s.count} inscrit${s.count>1?'s':''}</strong> · ${esc(state(s)[0])}</p><div class="controls"><label>Décision du club<select data-status="${s.id}"><option value="open" ${s.status==='open'?'selected':''}>Inscriptions ouvertes</option><option value="confirmed" ${s.status==='confirmed'?'selected':''}>Session confirmée</option><option value="cancelled" ${s.status==='cancelled'?'selected':''}>Session annulée</option></select></label><label>Message public<input data-note="${s.id}" maxlength="400" value="${esc(s.note)}"></label><button data-save="${s.id}">Enregistrer</button></div>${regs.length?`<div class="table-scroll"><table><thead><tr><th>Nageur</th><th>Groupe</th><th>E-mail de contact</th><th>Tarif</th><th>Action</th></tr></thead><tbody>${regs.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.group_name)}</td><td>${esc(r.email)}</td><td>${esc(r.price)}</td><td><button type="button" class="secondary" data-delete-registration="${esc(r.id)}" aria-label="Supprimer l’inscription de ${esc(r.name)} à ce créneau">Supprimer</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Aucun inscrit pour le moment.</p>'}</article>`;}).join('');const retired=adminData.registrations.filter(r=>r.retired);if(retired.length)$('adminSessions').insertAdjacentHTML('beforeend',`<article class="admin-session"><h3>Inscriptions à des créneaux retirés du planning</h3><p>Ces inscriptions restent conservées pour le suivi du club.</p><div class="table-scroll"><table><thead><tr><th>Créneau</th><th>Nageur</th><th>E-mail</th><th>Action</th></tr></thead><tbody>${retired.map(r=>`<tr><td>${esc(r.session.group)} · ${esc(label(r.session))}</td><td>${esc(r.name)}</td><td>${esc(r.email)}</td><td><button type="button" class="secondary" data-delete-registration="${esc(r.id)}">Supprimer</button></td></tr>`).join('')}</tbody></table></div></article>`);$('adminContent').hidden=false;$('adminLogin').hidden=true;}
$('adminLogin').onsubmit=async e=>{e.preventDefault();adminKey=$('adminKey').value.trim();try{await loadAdmin();$('adminKey').value='';message('');}catch(error){adminKey='';message(error.message);}};
$('adminRefresh').onclick=async()=>{try{await loadAdmin();message('');}catch(e){message(e.message);}};
$('adminLogout').onclick=()=>{adminKey='';adminData=null;$('adminContent').hidden=true;$('adminLogin').hidden=false;$('adminSessions').replaceChildren();$('adminStats').replaceChildren();};
$('adminSessions').onclick=async e=>{const remove=e.target.closest('[data-delete-registration]');if(remove){const registration=adminData.registrations.find(r=>r.id===remove.dataset.deleteRegistration);if(!registration)return;const session=adminData.sessions.find(s=>s.id===registration.session_id)||registration.session;if(!confirm(`Supprimer l’inscription de ${registration.name} au créneau ${label(session)} ? Cette suppression concerne uniquement ce créneau et ne peut pas être annulée.`))return;remove.disabled=true;try{await api('/api/admin/registration/delete',{body:{id:registration.id},key:adminKey});await loadAdmin();await load();message('Inscription supprimée. Les effectifs ont été mis à jour.');}catch(error){message(error.message);}finally{remove.disabled=false;}return;}const id=e.target.closest('[data-save]')?.dataset.save;if(!id)return;const status=document.querySelector(`[data-status="${id}"]`).value,note=document.querySelector(`[data-note="${id}"]`).value;try{await api('/api/admin/session',{body:{id,status,note},key:adminKey});await loadAdmin();await load();message('Décision enregistrée.');}catch(error){message(error.message);}};
$('exportCsv').onclick=async()=>{const button=$('exportCsv');button.disabled=true;try{await loadAdmin();const file=ROCExcel.create(adminData,minimum);download('ROC-inscriptions-et-totaux-Toussaint-2026.xlsx',file,file.type);message('Export Excel prêt : détail des inscriptions et totaux par adhérent.');}catch(error){message(error.message);}finally{button.disabled=false;}};
window.addEventListener('focus',()=>{if(view==='tracking')load();});
if('modelContext'in navigator){try{navigator.modelContext.registerTool({name:'afficher_stages',description:'Affiche le planning pour un groupe et une semaine sans inscrire de participant.',inputSchema:{type:'object',properties:{group:{type:'string',enum:['Tiny 1','Tiny 2','Tiny 3','Pèlerins','Mégalodons']},week:{type:'string',enum:['all','1','2']}},required:['group'],additionalProperties:false},execute:async args=>{$('group').value=args.group;$('week').value=args.week||'all';selected.clear();show('signup');render();return {content:[{type:'text',text:'Planning affiché.'}]};}});}catch{}}
load();
